#!/bin/bash
set -e

title="${1:-Qubes}"
text="${2:-Select qube:}"

qubes="$(python3 -c """
import sys
import qubesadmin
qubes = qubesadmin.Qubes()
for qube in qubes.domains:
    if qube.klass not in ('AppVM', 'StandaloneVM'):
        continue
    if qube.name.startswith('sys-') or qube.name.endswith('-dvm'):
        continue
    print(f'{qube.icon} {qube.name}')
""")"

echo -n "$(yad --list --modal --no-headers --width 150 --height 350 --title "$title" --text "$text" --column ':IMG' --column '' $qubes | cut -d '|' -f 2)"
