#!/bin/bash
set -e

path="$(mktemp --suffix .png)"
flameshot gui --raw > "$path"
qube="$(qubes-select-qube 'Flameshot' 'Select destination:')"
cat "$path" | qvm-run --pass-io "$qube" "cat | xclip -selection clipboard -target image/png -in"
rm "$path"
