#!/bin/bash
set -e

title="${1:-Qubes}"
text="${2:-Select qube:}"

qubes="$(python3 -c """
import sys
import qubesadmin
def is_system_qube(qube):
    if qube.klass not in ('AppVM', 'StandaloneVM'):
        return True
    if getattr(qube, 'template_for_dispvms', False):
        return True
    if 'servicevm' in qube.features:
        return True
    return False
for qube in sorted(qubesadmin.Qubes().domains, key=is_system_qube):
    print(f'{qube.icon} {qube.name}')
""")"

echo -n "$(yad --list --on-top --no-headers --width 150 --height 300 --title "$title" --text "$text" --column ':IMG' --column '' $qubes | cut -d '|' -f 2)"
